.TH FAXMSG 8
.SH NAME
faxmsg \- back end to faxabort, faxanswer and faxquit
.SH SYNOPSIS
.B /usr/sbin/faxmsg
.SH "DESCRIPTION"
.B faxmsg
is never called directly - it is always called by the names
.B faxabort, faxanswer,
or
.B faxquit.

This manual page was written for the Debian GNU/Linux distribution
(but may be used by others), because the original program does not
have a manual page.
.SH "SEE ALSO"
.IR hylafax (5),
.IR faxabort (8),
.IR faxanswer (8),
.IR faxquit (8)
.SH AUTHOR
This manual page was written by Dermot Bradley <bradley@debian.org>,
for the Debian GNU/Linux system.
