.TH LOCKNAME 8
.SH NAME
lockname \- generate a UUCP lock filename
.SH SYNOPSIS
.B /usr/sbin/lockname
.SH "DESCRIPTION"
.B lockname
is invoked by
.B faxaddmodem
and
.B probemodem
to generate a UUCP lock filename according to SVR4 conventions.

This manual page was written for the Debian GNU/Linux distribution
(but may be used by others), because the original program does not
have a manual page.
.SH "SEE ALSO"
.IR hylafax (5),
.IR faxaddmodem (8),
.IR probemodem (8)
.SH AUTHOR
This manual page was written by Dermot Bradley <bradley@debian.org>,
for the Debian GNU/Linux system.
