.TH ONDELAY 8
.SH NAME
ondelay \- open device without waiting for carrier
.SH SYNOPSIS
.B /usr/sbin/ondelay
.SH "DESCRIPTION"
.B ondelay
is invoked by
.B faxaddmodem
and
.B probemodem
to open a device without waiting for a carrier.

This manual page was written for the Debian GNU/Linux distribution
(but may be used by others), because the original program does not
have a manual page.
.SH "SEE ALSO"
.IR hylafax (5),
.IR faxaddmodem (8),
.IR probemodem (8)
.SH AUTHOR
This manual page was written by Dermot Bradley <bradley@debian.org>,
for the Debian GNU/Linux system.
