.TH TYPETEST 8
.SH NAME
typetest \- test out typerules
.SH SYNOPSIS
.B /usr/sbin/typetest
.I "[options] files"
.SH "DESCRIPTION"
The
.B typetest
script tests out typerules.

The
.I files
argument is the name of a file to test the rules on.

This manual page was written for the Debian GNU/Linux distribution
(but may be used by others), because the original program does not
have a manual page.
.SH OPTIONS
.TP
.BI \-f " rulesfile".
.SH "SEE ALSO"
.IR hylafax (5)
.SH AUTHOR
This manual page was written by Dermot Bradley <bradley@debian.org>,
for the Debian GNU/Linux system.
